name: Jason's first CI/CD Workflow
run-name: ${{github.actor}} is creating a CI/CD workflow 🚀

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world! 👋
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Install dependencies
        run: npm install
      - name: Run tests with Jest
        run: npm test
